version: "3.9"
services:
  database:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: "bank_project_db"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbuser"
    ports:
      - "5432:5432"
    restart: always
  application:
    build: .
    container_name: application
    depends_on:
      - database
    ports:
    - "8000:8080"
    restart: always