# Server
server:
  servlet:
    context-path: /bank-project
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true
  shutdown: graceful

spring:
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/bank_project_db
    driver-class-name: org.postgresql.Driver
    username: dbuser
    password: dbuser

  # Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml
    url: jdbc:postgresql://host.docker.internal:5432/bank_project_db
    user: dbuser
    password: dbuser

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true